
import React, { useState, useRef } from 'react';
import { Project, Source, SourceType } from '../types';
import { IconCamera, IconArrowLeft, IconCheck, IconClose, IconSparkles, IconUpload } from './Icons';
import { dataService } from '../services/dataService';
import { analyzePhysique } from '../services/geminiService';
import ReactMarkdown from 'react-markdown';

interface EvolutionGalleryProps {
    project: Project;
    onBack: () => void;
    onUpdateProject: (p: Project) => void;
}

const EvolutionGallery: React.FC<EvolutionGalleryProps> = ({ project, onBack, onUpdateProject }) => {
    const [selectedImages, setSelectedImages] = useState<Source[]>([]);
    const [isAnalyzing, setIsAnalyzing] = useState(false);
    const [comparisonResult, setComparisonResult] = useState<string | null>(null);
    const [isUploading, setIsUploading] = useState(false);
    
    const fileInputRef = useRef<HTMLInputElement>(null);

    // Filtra apenas fotos de shape
    const photos = project.sources
        .filter(s => s.type === SourceType.IMAGE && s.specificType === 'PHYSIQUE_CHECK')
        .sort((a, b) => {
            // Sort by date desc
            const dateA = a.date.split('/').reverse().join('-');
            const dateB = b.date.split('/').reverse().join('-');
            return new Date(dateB).getTime() - new Date(dateA).getTime();
        });

    const handleSelectImage = (source: Source) => {
        if (selectedImages.find(s => s.id === source.id)) {
            setSelectedImages(prev => prev.filter(s => s.id !== source.id));
        } else {
            if (selectedImages.length < 2) {
                setSelectedImages(prev => [...prev, source]);
            } else {
                // Replace the oldest selection if trying to select a 3rd
                setSelectedImages(prev => [prev[1], source]);
            }
        }
    };

    const handleCompare = async () => {
        if (selectedImages.length !== 2) return;
        setIsAnalyzing(true);
        setComparisonResult(null);

        try {
            // Need to fetch file Blobs/Files from URLs or Storage
            // For simplicity, assuming we can get the file via dataService helper or fetch
            // But since we store filePath, we might need a signedURL to fetch.
            // Let's simulate creating dummy files if we can't easily refetch binaries here without more backend logic.
            // *CORRECT APPROACH*: In a real app, we fetch the blobs. Here, assuming we might need to re-upload or
            // pass URLs if the API supported it. Gemini API via JS SDK usually needs Base64.
            // Since we don't have the original File objects here, we will fetch the images via their URLs.
            
            const filePromises = selectedImages.map(async (src) => {
                if (!src.fileUrl) throw new Error("URL da imagem não disponível");
                const response = await fetch(src.fileUrl);
                const blob = await response.blob();
                return new File([blob], src.title, { type: blob.type });
            });

            const files = await Promise.all(filePromises);
            const result = await analyzePhysique(files, true); // true = comparison mode
            setComparisonResult(result);

        } catch (error) {
            console.error(error);
            alert("Erro ao comparar imagens. Verifique se os arquivos são acessíveis.");
        } finally {
            setIsAnalyzing(false);
        }
    };

    const handleUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
        if (!e.target.files || e.target.files.length === 0) return;
        const file = e.target.files[0];
        
        setIsUploading(true);
        try {
            // 1. Upload Storage
            const userId = (await dataService.getUserProfile(project.id))?.id || 'unknown'; // Quick fix to get ID, or pass via props
            // Actually dataService needs userId. Let's assume we can get it from session in dataService.
            const { data: { session } } = await import('../lib/supabase').then(m => m.supabase.auth.getSession());
            
            if (!session) throw new Error("Não autenticado");

            const filePath = await dataService.uploadFileToStorage(file, session.user.id, project.id);
            if (!filePath) throw new Error("Falha no upload");

            // 2. Analyze Single Image
            const analysis = await analyzePhysique([file], false);

            // 3. Save to Sources
            const today = new Date().toLocaleDateString('pt-BR');
            const newSource: Source = {
                id: '', // Generated by DB
                title: `Check Shape ${today}`,
                type: SourceType.IMAGE,
                specificType: 'PHYSIQUE_CHECK',
                date: today,
                content: analysis, // Save analysis as content
                summary: 'Análise de Físico (IA)',
                selected: true,
                filePath: filePath
            };

            await dataService.addSource(project.id, newSource);
            
            // Reload project (Trigger callback)
            // Ideally we should just append locally but onUpdateProject usually expects full reload logic
            // Let's trigger a refresh via callback
            // For now, simple alert or let parent handle refresh via dataService listener if implemented
            alert("Foto enviada e analisada com sucesso!");
            
            // Force reload by calling something or just accept user will see it next refresh
            // Ideally we call onUpdateProject with new source appended
            // We need to re-fetch sources to get the ID.
            const updatedProject = await dataService.getOrCreateProject(session.user.id);
            if(updatedProject) onUpdateProject(updatedProject);

        } catch (err) {
            console.error(err);
            alert("Erro no upload.");
        } finally {
            setIsUploading(false);
            if (fileInputRef.current) fileInputRef.current.value = '';
        }
    };

    return (
        <div className="flex flex-col h-full bg-gray-50 dark:bg-gray-950 absolute inset-0 z-50 overflow-hidden">
            {/* Header */}
            <div className="bg-white border-b border-gray-200 px-4 py-4 flex items-center justify-between dark:bg-gray-900 dark:border-gray-800 shrink-0">
                <div className="flex items-center gap-3">
                    <button onClick={onBack} className="p-2 hover:bg-gray-100 rounded-full dark:hover:bg-gray-800">
                        <IconArrowLeft className="w-5 h-5 text-gray-600 dark:text-gray-300" />
                    </button>
                    <div>
                        <h2 className="text-lg font-bold text-gray-900 dark:text-white flex items-center gap-2">
                            <IconCamera className="w-5 h-5 text-purple-600" />
                            Galeria de Evolução
                        </h2>
                        <p className="text-xs text-gray-500 dark:text-gray-400">Compare seu progresso visual</p>
                    </div>
                </div>
                
                <div className="flex gap-2">
                    <input type="file" ref={fileInputRef} className="hidden" accept="image/*" onChange={handleUpload} />
                    <button 
                        onClick={() => fileInputRef.current?.click()}
                        disabled={isUploading}
                        className="flex items-center gap-2 px-4 py-2 bg-black text-white rounded-lg text-xs font-bold hover:bg-gray-800 transition-colors dark:bg-blue-600 dark:hover:bg-blue-700"
                    >
                        {isUploading ? 'Analisando...' : <><IconUpload className="w-4 h-4" /> Novo Check</>}
                    </button>
                </div>
            </div>

            {/* Content Area */}
            <div className="flex-1 overflow-hidden flex flex-col md:flex-row">
                
                {/* Photo Grid */}
                <div className="flex-1 overflow-y-auto p-4 custom-scrollbar">
                    {photos.length === 0 ? (
                        <div className="flex flex-col items-center justify-center h-full opacity-50">
                            <IconCamera className="w-16 h-16 text-gray-300 mb-4" />
                            <p className="text-sm text-gray-500">Nenhuma foto de físico registrada.</p>
                        </div>
                    ) : (
                        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
                            {photos.map(photo => {
                                const isSelected = selectedImages.find(s => s.id === photo.id);
                                return (
                                    <div 
                                        key={photo.id} 
                                        onClick={() => handleSelectImage(photo)}
                                        className={`relative aspect-[3/4] rounded-xl overflow-hidden cursor-pointer border-2 transition-all group ${
                                            isSelected 
                                            ? 'border-purple-600 ring-2 ring-purple-200 dark:ring-purple-900' 
                                            : 'border-transparent hover:border-gray-300 dark:hover:border-gray-700'
                                        }`}
                                    >
                                        <img 
                                            src={photo.fileUrl} 
                                            alt={photo.title} 
                                            className="w-full h-full object-cover"
                                            loading="lazy"
                                        />
                                        <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent opacity-100 md:opacity-0 group-hover:opacity-100 transition-opacity" />
                                        
                                        <div className="absolute bottom-2 left-2 right-2">
                                            <p className="text-white text-xs font-bold truncate">{photo.date}</p>
                                        </div>

                                        {isSelected && (
                                            <div className="absolute top-2 right-2 bg-purple-600 text-white p-1 rounded-full shadow-sm">
                                                <IconCheck className="w-3 h-3" />
                                            </div>
                                        )}
                                    </div>
                                );
                            })}
                        </div>
                    )}
                </div>

                {/* Comparison / Analysis Panel */}
                {(selectedImages.length > 0 || comparisonResult) && (
                    <div className="w-full md:w-96 bg-white border-l border-gray-200 flex flex-col shadow-xl z-20 dark:bg-gray-900 dark:border-gray-800 h-[40vh] md:h-full">
                        
                        <div className="p-4 border-b border-gray-100 flex justify-between items-center dark:border-gray-800">
                            <h3 className="font-bold text-sm text-gray-800 dark:text-white flex items-center gap-2">
                                {comparisonResult ? <><IconSparkles className="w-4 h-4 text-purple-500" /> Análise Comparativa</> : 'Seleção'}
                            </h3>
                            <button onClick={() => { setSelectedImages([]); setComparisonResult(null); }} className="text-gray-400 hover:text-gray-600">
                                <IconClose className="w-4 h-4" />
                            </button>
                        </div>

                        <div className="flex-1 overflow-y-auto p-4 custom-scrollbar">
                            {comparisonResult ? (
                                <div className="prose prose-sm dark:prose-invert text-xs leading-relaxed">
                                    <ReactMarkdown>{comparisonResult}</ReactMarkdown>
                                </div>
                            ) : (
                                <div className="space-y-4">
                                    <p className="text-xs text-gray-500 dark:text-gray-400">
                                        {selectedImages.length === 1 
                                            ? "Selecione outra foto para comparar." 
                                            : "Duas fotos selecionadas. Pronto para comparar."}
                                    </p>
                                    
                                    <div className="grid grid-cols-2 gap-2">
                                        {selectedImages.map((img, i) => (
                                            <div key={img.id} className="relative rounded-lg overflow-hidden aspect-square border border-gray-200 dark:border-gray-700">
                                                <img src={img.fileUrl} className="w-full h-full object-cover" />
                                                <div className="absolute bottom-0 left-0 right-0 bg-black/50 text-white text-[10px] p-1 text-center font-bold">
                                                    {i === 0 ? 'A (Antiga?)' : 'B (Recente?)'}
                                                </div>
                                            </div>
                                        ))}
                                    </div>

                                    {selectedImages.length === 1 && selectedImages[0].content && (
                                        <div className="mt-4 p-3 bg-gray-50 rounded-lg border border-gray-100 dark:bg-gray-800 dark:border-gray-700">
                                            <span className="text-[10px] font-bold text-gray-400 uppercase mb-1 block">Análise Individual</span>
                                            <div className="text-xs text-gray-600 dark:text-gray-300 line-clamp-6">
                                                <ReactMarkdown>{selectedImages[0].content}</ReactMarkdown>
                                            </div>
                                        </div>
                                    )}
                                </div>
                            )}
                        </div>

                        <div className="p-4 border-t border-gray-100 dark:border-gray-800">
                            {selectedImages.length === 2 && !comparisonResult && (
                                <button 
                                    onClick={handleCompare}
                                    disabled={isAnalyzing}
                                    className="w-full py-3 bg-purple-600 text-white font-bold text-sm rounded-xl hover:bg-purple-700 transition-colors shadow-lg shadow-purple-500/20 disabled:opacity-70 flex items-center justify-center gap-2"
                                >
                                    {isAnalyzing ? (
                                        <>
                                            <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                                            Comparando...
                                        </>
                                    ) : (
                                        <>
                                            <IconSparkles className="w-4 h-4" /> Comparar Evolução
                                        </>
                                    )}
                                </button>
                            )}
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};

export default EvolutionGallery;
